### ISSUE TITLE
missing picofeed ? 

### ISSUE THREAD

**Issue by michield** [bramley/phplist-plugin-rssfeed#1]
fetch rss items

Fatal error: Class 'PicoFeed\Config\Config' not found in RssFeedPlugin/get.php on line 32

**Comment by bramley** [comment]
The PicoFeed package is within CommonPlugin. If you are using a fork of the github repository then is it up to date?

**Comment by michield** [comment]
Ah, ok, will check

**Comment by michield** [comment]
Now it's saying 

Fatal error: Class 'RssFeedPlugin_DAO' not found in RssFeedPlugin/get.php on line 34

**Comment by michield** [comment]
ah, that's in the DAO file. I was looking for a RssFeedPlugin_DAO file.

**Comment by bramley** [comment]
I'm unsure why you are having these missing class problems. There is an autoloader that should find them all.

**Comment by michield** [comment]
the autoloader assumes everything in one "plugins" folder. In my case, that's not true.

I've sorted it by adding all locations to the PLUGIN_ROOTDIRS

**Comment by bramley** [comment]
I don't follow this. The autoloader uses the same approach for plugin locations as the code in pluginlib.php, i.e. split PLUGIN_ROOTDIRS and PLUGIN_ROOTDIR
What other locations for plugins do you expect to work?
