### ISSUE TITLE
commandline error

### ISSUE THREAD

**Issue by michield** [bramley/phplist-plugin-rssfeed#11]
When trying to run the cron, I get 

PHP Fatal error:  Class '_Controller_Cron' not found in /home/michiel/git/michield/phplist-plugin-rssfeed/plugins/RssFeedPlugin/ControllerFactory.php on line 36

**Comment by bramley** [comment]
What is the command that you are using?

**Comment by michield** [comment]
phplist -pcron

I guess it's related to how the plugin pages are called from the central cron. Still checking.

**Comment by michield** [comment]
The way you wrote it requires calling 

 phplist -m RssFeedPlugin -p get

**Comment by bramley** [comment]
Yes that's how command line pages are run. Is your new approach documented anywhere? 
I will need to understand what you are trying to do before I can change this, and some other, plugins to fit in with it.

**Comment by michield** [comment]
it's fine. I will update the cron system, as that's not ready yet and can be changed. I am trying to make it work so that you only need one cron process and everything that needs doing is managed in the application, instead of having to set up a cron for each process.

**Comment by bramley** [comment]
The code was unnecessarily over-elaborate. This change removes the dependencies on $_GET.
If you replace the content of RssfeedPlugin/get.php with this then the cron.php code should be able to include the file.
You will also need to upgrade Common Plugin first.

```
if (!(phplistPlugin::isEnabled('CommonPlugin'))) {
    echo "phplist-plugin-common must be installed and enabled to use this plugin";
    return;
}

$controller = new RssFeedPlugin_Controller_Get();
$controller->run();
```
