### ISSUE TITLE
Menu integration seems broken

### ISSUE THREAD

**Issue by singinwhale** [bramley/phplist-plugin-rssfeed#18]
It seems to me as if the rssfeed plugin is not able to display its own menu items anymore. Either the plugin doesn't work or I can't see the menu Items.

I am using PHPList v3.3.1 with the phplist-ui-bootlist theme. I installed it via the integrated plugins installer and its displaying in the plugins list.

**Comment by michield** [comment]
Is it ok when you switch themes?

**Comment by singinwhale** [comment]
Nope. Doesn't work in dressprow either.

**Comment by bramley** [comment]
The menu items are displayed in release 3.3.1

![image](https://cloud.githubusercontent.com/assets/3147688/24082864/410bbe68-0cc4-11e7-9f72-89dfc906bb5c.png)

Have you enabled the plugin?

**Comment by singinwhale** [comment]
Alright... That worked. Thanks a lot!
In the Bootlist theme (aka. Trevelin) the controls are just nonexistent for disabled plugins so I didn't even know that you could do that. As nice as Trevelin looks i will stick with the old one if it is that buggy.

Thank you very much for the support :)
I think I will file a bug report for the Trevelin...
