### ISSUE TITLE
forwarding an RSS campaign doesn't work

### ISSUE THREAD

**Issue by edgimar** [bramley/phplist-plugin-rssfeed#19]
At the end of each message there is a line that says "To forward this message, please do not use the forward button of your email application, because this message was made specifically for you only. Instead use the _forward_ page in our newsletter system."  If you click on the _forward_ link, and provide an email address, then the email which gets forwarded only contains the `[RSS]` placeholder and not the actual message text that was originally generated by the rssfeed plugin.

Maybe there's no way to remedy this problem, but ideally, the _forward_ link would contain enough information for phplist to know which RSS feed info to use to replace the `[RSS]` placeholder with.

**Comment by bramley** [comment]
This should work, so long as you wait until phplist has completed sending the campaign before forwarding. Ensure that you are using the latest release of the plugin.

**Comment by edgimar** [comment]
I installed the plugin last October, and I see that commit 1713b261d (December 4) appears to be when this was fixed, so I'll assume that this is no longer an issue - thanks!
