### ISSUE TITLE
only one item

### ISSUE THREAD

**Issue by michield** [bramley/phplist-plugin-rssfeed#2]
still searching the cause, but thought I'd flag it up. I set it up, kept everything to be the defaults, and added a BBC newsfeed. The campaign only had one RSS item in the body of the message, instead of the 30 I expected it to have.

**Comment by bramley** [comment]
If it is an hourly repeat, then only items published in the 60 minutes preceding the embargo time will be selected. It won't select any items with an earlier published date/time even if they were retrieved in the past 60 minutes.

**Comment by michield** [comment]
yes, all fine
