### ISSUE TITLE
Cannot retrieve some feed in test message

### ISSUE THREAD

**Issue by enboig** [bramley/phplist-plugin-rssfeed#20]
I have just installed the plugin, and I am trying to use this rss:
https://www.escoltesiguies.cat/rss
The fields don't seem to be standard, so I added this to template:
    [title]
    [pubDate]
    [description]
    [link]

But test message just include test items.
Where is the "retrieve feed items" button or link? I cannot see it.

Thanks

**Comment by bramley** [comment]
Please see the plugin documentation https://resources.phplist.com/plugin/rssfeed#retrieving_rss_feed_items

**Comment by enboig** [comment]
You are right, I didn't read the full document before asking.

Sorry, and thanks for your plugin
