### ISSUE TITLE
Date format configuration

### ISSUE THREAD

**Issue by da2x** [bramley/phplist-plugin-rssfeed#22]
The date format used in `[PUBLISHED]` default to locale default and also be configurable.

**Comment by bramley** [comment]
Sorry but I don't understand what you are asking. Please can you explain exactly what the problem is?

**Comment by da2x** [comment]
The date format string is hardcoded. It should be configurable.

https://github.com/bramley/phplist-plugin-rssfeed/blob//915f3c30e368fd26cadfc500aa3575d7ee0b9fd7/plugins/RssFeedPlugin.php#L149

**Comment by bramley** [comment]
I have added a configuration setting to specify the format string for the published date. The format options are explained at http://php.net/manual/en/function.date.php

**Comment by da2x** [comment]
Perfect! Thank you.
