### ISSUE TITLE
Allow manual plain-text formatting

### ISSUE THREAD

**Issue by da2x** [bramley/phplist-plugin-rssfeed#23]
By default, the RSS template doesn’t convert well to plain-text and there is no way to manually adjust it. The biggest problem is that HTML links isn’t converted to plain-text links (this happens automatically for links in the content template).

1. Enable `define('USE_MANUAL_TEXT_PART', 1);`

This gives you one template for content in HTML and one for plain-text.

This option should also trigger a separate template for plain-text formatting for the RSS template.

So this is actually two issues: 1) links don’t convert to plain-text by default, and 2) the plain-text RSS template should be configurable. Reporting them as one issue as solving either would solve my problem.

**Comment by da2x** [comment]
The conversion in core happens in HTML2Text:

https://github.com/phpList/phplist3/blob/9ec0dba0b2ccc403d21a2f5fcc0c05b52e5186a6/public_html/lists/admin/inc/maillib.php#L22-L23

It looks like it should work for the RSS template too. Does processing happen too late, perhaps?

**Comment by bramley** [comment]
Using the default rss template and the BBC feed http://feeds.bbci.co.uk/news/rss.xml?edition=uk , this is the html in the resultant email for one item

```
<a href="http://strontian/lists/lt.php?tid=KUlRAgwDVlADAhoHVwcBSQ1UBgccXAZRVE4EBwZUUQdQBFQAAANMVFRUUlMGBlNJAVAOBxxQAAQHTgoEXAEZDlUEVFdQXQdSWVYBTVUFAgcOUgBWHAYGA1VOB1BWBhlXUAYHSVEBAwMFVwQEUFJSAA" ><b>Jamal Khashoggi: Saudi Arabia calls murder claims 'lies'</b></a><br/>
13/10/2018 06:48<br/>
Turkish officials say journalist Jamal Khashoggi was tortured and killed in the Saudi consulate.
<hr/>
```
and this is the text, generated through HTML2Text()
```
 *Jamal Khashoggi: Saudi Arabia calls murder claims 'lies'*
<http://strontian/lists/lt.php?tid=T5/yt2/OjgOFAH+34REdX2Wut7eKg7PsnouEET6HCMba/HxrtbExLqE73TrbNaZt>

 13/10/2018 06:48

 Turkish officials say journalist Jamal Khashoggi was tortured and killed
in the Saudi consulate.
```
In this case the item title and description contain only plain text, but in general they can be html. I think that there is no avoiding having to convert html to plain text at some point.

I do not think that having a separate rss template for the plain text email would remove the need to convert item title and description from html to text.

**Comment by bramley** [comment]
> It looks like it should work for the RSS template too

The plugin calls HTML2Text() on the html generated for all the items. If that does not look correct in your case then perhaps there is a problem in HTML2Text. So far as I can see links in the html are converted correctly.

```
$this->rssHtml = $this->generateItemHtml($items, $messageData['rss_order'], $messageData['rss_template']);
$this->rssText = HTML2Text($this->rssHtml);
```

**Comment by da2x** [comment]
My RSS template:

    <article>
      <a href="[URL]"><h3>[TITLE]</h3></a>
      [CONTENT]
    </article>

Generated plain text:

    **The item title**
    
    The item content.

The link just disappears in the plain-text variant. I’ve tried removing the article and h3 elements and the only thing that changes is that the asterisks surrounding the title disappears.

I’ve tried using a custom RSS template for the campaign, and I’ve tried using the system-wide RSS template in settings. Both template removes all links.

I’ve also restored the default template and it also doesn’t have any links in the plain text variant.

**Comment by da2x** [comment]
This might be something … The template [URL] prints the source link (without tracking) in the HTML template and prints the tracking link in the plain text variant.  Could that be a symptom of the underlying issue?

With this template, the first link doesn’t work while the second does work. Both work in HTML mode.

    <p>Example text with <a href="[URL]">link</a></p>
    <p>Example text with <a href="https://www.phplist.org">link</a></p>

**Comment by da2x** [comment]
Oh, expletive. This triggered but only for plain-text and not HTML.

https://github.com/phpList/phplist3/pull/414

Sorry for wasting your time on this.
