### ISSUE TITLE
PHP8 compatibility

### ISSUE THREAD

**Issue by michield** [bramley/phplist-plugin-rssfeed#24]
I presume this needs fixing upstream, but I get this error on PHP8

<b>Fatal error</b>:  Array and string offset access syntax with curly braces is no longer supported in <b>/var/www/phpList3/public_html/lists/admin/plugins/phplist-plugin-rssfeed/plugins/RssFeedPlugin/vendor/fguillot/picofeed/lib/PicoFeed/Client/Url.php</b> on line <b>143</b>

**Comment by bramley** [comment]
The upstream repository has now disappeared, so I will be treating the picofeed library as part of the plugin code and will make a change to that. There are some forks of the original repository but unless any serious problem arises I'm happy staying with the current code.
