### ISSUE TITLE
Option to use the full post content as the content, even if shorter description is available

### ISSUE THREAD

**Issue by Skyedra** [bramley/phplist-plugin-rssfeed#27]
Hello,

First, thank you for creating this plugin!  I'm excited to use it to help visitors keep updated on my blog posts.

On my blog, I create descriptions for most posts.  This way, if the post url is shared on Discord or other social media, an easily digestible description can be included.  

However, for something like an e-mail, I'd like to mail the whole post to my readers so they don't even need to visit the site.  (The way I have it set up right now, I am using content for full content, and configured the description tag in the additional feeds feature.  In my template, I then preface the description before the post title, which is a nice way for users to be able to see the most important part of the description in the e-mail preview and then open the mail to read the rest.)

So, I would like to suggest a system option to have the full post content as the content, even if shorter description is available.

Then, in `admin/plugins/RssFeedPlugin/Controller/Get.php` the `getItemContent` function can check this variable and return the full content if configured.

I'm not sure how difficult it is to add additional phplist options, but I was able to hardcode this in a couple lines for getItemContent, so hopefully this would be a simple, useful feature to add :)

**Comment by bramley** [comment]
You should be able to add the element whose content you want to use as a custom tag, then use a placeholder for that tag. See the plugin documentation for an example  https://resources.phplist.com/plugin/rssfeed#custom_tags

**Comment by Skyedra** [comment]
A fair suggestion, but I happened to try that already earlier today and encountered a strange unicode issue when importing RSS:

`Database error 1366 while doing query Incorrect string value: '\xF0\x9F\x98\x89" ...' for column 'value' at row 9`

That post had a winking face emoji in it, and I suspect that broke the import process.  When content:encoded is imported into the database, it doesn't have this problem when imported as content, only when imported as a custom tag.

**Comment by bramley** [comment]
That's caused by the phplist database using utf8 instead of utf8mb4, which restricts characters to 3 bytes instead of 4 bytes, see https://mantis.phplist.org/view.php?id=20109
I can probably fix that problem in the plugin by explicitly converting 4-byte characters to html entities. Can you give me the feed URL so that I can test it?

**Comment by Skyedra** [comment]
Ok!  Is there a way I can send you the feed url privately?

**Comment by bramley** [comment]
You can update the plugin to test the change using this package URL https://github.com/bramley/phplist-plugin-rssfeed/archive/custom_tag_entities.zip

It is only a 1-line change so should not break anything.

**Comment by Skyedra** [comment]
Awesome, that fixed the crash!

The only downside to using this method is it means the content parsing stuff isn't being done.  So, for instance, there's a bunch of missing wordpress styles being applied, and I bet things like iframes, etc wouldn't be reformatted either (I use them occasionally, but not recently enough to have it in my feed).

**Comment by bramley** [comment]
I have implemented your suggestion, a configuration setting to use either the summary or full content. The default is to use the summary so you need to change that.
Upgrade the plugin using the original package URL `https://github.com/bramley/phplist-plugin-rssfeed/archive/master.zip`

**Comment by Skyedra** [comment]
That's working great!  Thank you so much!
