### ISSUE TITLE
Add table of contents (TOC) of feed items? [enhancement]

### ISSUE THREAD

**Issue by talgalili** [bramley/phplist-plugin-rssfeed#28]
In the feedburner email campaigns, there was the option of getting the email so that at the top we'd see a TOC with the titles of each of the feed items that are in the email.
When any of them were clicked, it would bring the user to the part of the email that had that text (anchor link).

Is it possible to do in the current plugin? (if not, is it possible to add it?)

Thanks upfront,
T

**Comment by bramley** [comment]
I did some work on having a table of contents a while ago. The changes work but the awkward part is how to handle the styling of the TOC. Do you have an example of how feedburner shows it, which you would be happy with? I expect that someone else might want a slightly different layout to you, so it needs to be configurable in some way.
This is how it appears using my development version of the plugin

![image](https://user-images.githubusercontent.com/3147688/134873882-57ab6d76-3daf-4912-a8c9-b290cf836a79.png)

**Comment by talgalili** [comment]
Thanks, it's just a simple list `<li>`, looking like this:

![image](https://user-images.githubusercontent.com/976006/134880457-d068769f-6e09-439c-ba9b-45924e374605.png)


WDY?T

**Comment by bramley** [comment]
I have pushed my development branch if you would like to try it.

On the Manage Plugins page install using the URL `https://github.com/bramley/phplist-plugin-rssfeed/archive/toc.zip` which will replace the current plugin.
There is a new configuration setting to include a table of contents, the default is not to.

**Comment by talgalili** [comment]
@bramley 
It works great - thanks!
What I think would make it better is the ability to use it with some tag (say [TOC]), and then modify the text before/after it.
For example

Posts in this e-mail:
[TOC]
<rest of the template>

What do you think?

How it looks right now (which helps show why it would benefit from some extra text)

![image](https://user-images.githubusercontent.com/976006/134936230-20bc6dc2-d105-4a52-93eb-be2751beb2b5.png)

**Comment by bramley** [comment]
Using a placeholder does provide more flexibility. I have added that, so you can include the placeholder RSS:TOC in the message content with some text or html markup before or after it, followed by the RSS placeholder.

![image](https://user-images.githubusercontent.com/3147688/134991463-56015aa6-09d9-4b34-a978-8b8bd54b85c4.png)

The configuration setting is no longer used.

You can update the plugin on the Manage Plugins page, still the development branch.

**Comment by talgalili** [comment]
Just tested, I can confirm it works.
Thanks for being so fast and responsive!

**Comment by bramley** [comment]
I made a release yesterday and the development branch has now been removed.. You can go back to using the URL `https://github.com/bramley/phplist-plugin-rssfeed/archive/master.zip` to install the plugin.
