### ISSUE TITLE
[feature request] add setting option to control "maximum numbers of past days to look for new posts"

### ISSUE THREAD

**Issue by talgalili** [bramley/phplist-plugin-rssfeed#31]
In feedburner email there was a nice thing: it would look at the feed and whatever content was in it, that wasn't before, would be sent in the next email.
So for example, if we are sending a daily email, it might be that the feed would (for some reason) include a post from 3 days ago, then feedburner would send it on the next go-around (since it wasn't sent in the past email).

It would be great to add this control also to the 'rssfeed' plugin. The current default is that if we send a daily email, it will only send items from the RSS from the past 1 day, but would ignore items that might have been added that happen to be in the past (say) 3 days.

I think this would be very helpful (especially when changing post dates due to various other considerations).

**Comment by michield** [comment]
Isn't this already the case? If I read [the docs](https://resources.phplist.com/plugin/rssfeed) it says

> The repeat frequency can be hourly, daily, weekly, fortnightly, or four-weekly. Which interval is suitable depends on the content that you are using and how often it changes. Probably daily or weekly are the most suitable.
> 
> When the campaign is being sent, the plugin selects feed items based on the repeat interval:
> 
>     'day' - items whose published date is within the past 24 hours
>     'week' - items whose published date is within the past 7 days
>     'fortnightly' - items whose published date is within the past 14 days
>     'four-weekly' - items whose published date is within the past 28 days
> 

So, basically, you can control this with your repeat frequency.

**Comment by bramley** [comment]
The processing uses the publication date, not the date that the item was received. The problem being raised is when an item is sent with an old publication date, which stops it being selected.

A change that I have looked at but didn't ever complete is to use the "received" date instead of the publication date, or give the choice of which to use. It needs a bit more analysis to ensure that items are not duplicated if they are sent more than once.

**Comment by talgalili** [comment]
That would be very helpful. (It's a great thing that feedburner had, and
tools such as follow.it don't have).

Maybe combine the two?
Received in the last day, published in the last X days (say 3).
WDYT?

**Comment by bramley** [comment]
I think that it would have to be to use the published date or use the received date, with an option as which to use. That looks to be straightforward to implement. Adding a published threshold is going to be more complex, which I'm not keen to implement.

**Comment by talgalili** [comment]
That sounds great, would love to test it!

T

**Comment by bramley** [comment]
There is a new release of the plugin that lets you choose the date for selecting feed items - published or added. That is implemented as a drop-down on the RSS tab when editing a campaign, so it can be specific to each campaign.

This requires Common Plugin to be upgraded first, and also requires php 7 or later.

**Comment by talgalili** [comment]
Cool, thanks!
