### ISSUE TITLE
Use content rather than summary from Atom feed

### ISSUE THREAD

**Issue by edent** [bramley/phplist-plugin-rssfeed#34]
Thanks for this really useful plugin. I'm having a bit of trouble configuring it to send the full content of the feed.

I've set the summary configuration to No:

![Setting](https://github.com/user-attachments/assets/d4c03893-7676-48b8-96be-edb84be38f67)

But my test emails are still only showing the summary.

![Email](https://github.com/user-attachments/assets/af75d083-cd85-4e3a-9357-287ec27ad062)

My campaign's custom template is:

```html
<div>
  <h1><a href="[URL]">[TITLE]</a></h1>
  <p>[CONTENT]</p>
</div>
```

And the content is `[RSS]`

The feed I'm using is: https://shkspr.mobi/blog/feed/atom/

Is there a different setting or option I should be using?

**Comment by bramley** [comment]
Just tried your feed and received an email with the full content

![image](https://github.com/user-attachments/assets/3f4be4f4-9f89-4f9b-bd06-e82d0ae7f4c1)

The distinction between whether to use summary or content is used when fetching the feed items. If you had summary initially and fetched the feed then only the summary will have been stored, even if you later changed to use the content element. You might be able to confirm that by looking at the Feed Items page, menu Campaigns > RSS Feeds, then click the number of items.

You probably need to clear the feed items and fetch them again. You can clear them through menu Campaigns > Delete outdated feed items then set the number of days to 0, which will remove everything.

**Comment by edent** [comment]
Yup, clearing the feed did it. Many thanks!
