### ISSUE TITLE
RSS Feed Rendering Order Issue in phpList

### ISSUE THREAD

**Issue by john-executivemosaic** [bramley/phplist-plugin-rssfeed#35]
Hi, I just don't know where to reach out regarding our problem because the forum in the documentation doesnt work anymore.

So this is our problem regarding RSS feed in phplist.
Our RSS feed sequence is like this
```
- Story 01
- Story 02
- Story 03
- Story 04
- Story 05
- Story 06
- Story 07
- Story 08
- Story 09
- Story 10  
```

But when rendering the RSS feed in our email template, the order jumbles and it goes like this
```
- Story 03
- Story 02
- Story 01
- Story 06
- Story 05
- Story 04
- Story 09
- Story 08
- Story 07
- Story 10
```

at first I thought that it's sorting it based on pubdate but when I checked all the stories, it's not.

The RSS feed version that we're using is `2.5.6+20180517`. Thank you!

**Comment by bramley** [comment]
The items should be ordered by the published date, in either ascending or descending order. You can see the published date on the Feed Items page, menu Campaigns > RSS Feeds then click the number in the Items column.

Also you are using a very old version of the plugin and I recommend upgrading on the Manage Plugins page.

**Comment by john-executivemosaic** [comment]
This is the only available option from our current version.
<table>
<tr>
<td>

![image](https://github.com/user-attachments/assets/ef920235-792a-4774-abd8-f58a2238109a)

</td>
<td>

![image](https://github.com/user-attachments/assets/34569d82-55e6-4ff2-bb93-7f6b9b0b2402)

</td>
</tr>
</table>



> Also you are using a very old version

I agree with you. I have raised this with our admin, and we will be updating it over the weekend.
Thank you!

**Comment by bramley** [comment]
I don't recognise the "Send a campaign" screenshot. It looks like you have had someone modify the plugin. In that case I can't help with any problems that you have.

**Comment by john-executivemosaic** [comment]
Alright, thank you so much! I guess I'm gonna have to study the codebase and modify it as well since we don't have the dev who did it before. I will close this ticket now. Thank you!
